import type {
  WpBroadcastArchive,
  WpEvent,
  WpFaq,
  WpNews,
} from "@/types/wordpress";

/**
 * ヘッドレスWP未構築期間中のフォールバック用モック。
 *
 * 形は本物のWP REST API（`?_embed=true`）の返却JSONに合わせている。
 * `WP_API_BASE_URL` が未設定のとき `wp-api.ts` がこれを返す。
 *
 * Sprint 1 でWP構築完了後はこのファイルを直接消さず、
 * テスト・Storybook用のフィクスチャとして残す想定。
 */

const ISO = (date: string, time = "09:00:00") => `${date}T${time}`;

const renderHtml = (paragraphs: string[]): string =>
  paragraphs.map((p) => `<p>${p}</p>`).join("\n");

export const mockWpNews: WpNews[] = [
  {
    id: 1001,
    date: ISO("2026-03-01"),
    date_gmt: ISO("2026-03-01", "00:00:00"),
    modified: ISO("2026-03-01"),
    modified_gmt: ISO("2026-03-01", "00:00:00"),
    slug: "reiwa8-soukai-shiryo",
    status: "publish",
    type: "news",
    link: "https://cms.hassamu-izumi.jp/news/reiwa8-soukai-shiryo/",
    title: { rendered: "令和8年度の総会資料を公開しました" },
    content: {
      rendered: renderHtml([
        "令和8年度の発寒泉町内会 定期総会に使用する資料をデジタル公開いたしました。会員の皆様は事務局からお送りした URL より内容をご確認ください。",
        "紙資料をご希望の方は、班長または事務局までお声がけください。",
      ]),
      protected: false,
    },
    excerpt: {
      rendered: "<p>令和8年度 定期総会の資料をデジタル公開いたしました。</p>",
      protected: false,
    },
    featured_media: 0,
    acf: { category: "お知らせ", pinned: true, summary: "令和8年度 定期総会の資料をデジタル公開いたしました。" },
  },
  {
    id: 1002,
    date: ISO("2026-02-25"),
    date_gmt: ISO("2026-02-25", "00:00:00"),
    modified: ISO("2026-02-25"),
    modified_gmt: ISO("2026-02-25", "00:00:00"),
    slug: "izumi-park-yuugu-tenken",
    status: "publish",
    type: "news",
    link: "https://cms.hassamu-izumi.jp/news/izumi-park-yuugu-tenken/",
    title: { rendered: "発寒泉公園の遊具点検について" },
    content: {
      rendered: renderHtml([
        "発寒泉公園の遊具安全点検を、2026年3月5日 9:00〜12:00 に実施いたします。",
        "点検中は一部の遊具が使用禁止となります。お子様の利用にはご注意ください。",
      ]),
      protected: false,
    },
    excerpt: {
      rendered: "<p>発寒泉公園の遊具安全点検を実施いたします。</p>",
      protected: false,
    },
    featured_media: 2001,
    acf: { category: "生活情報", summary: "遊具安全点検中は一部利用不可。" },
    _embedded: {
      "wp:featuredmedia": [
        {
          id: 2001,
          source_url:
            "https://images.unsplash.com/photo-1573749057236-a76eddbcfaab?auto=format&fit=crop&q=80&w=1200",
          alt_text: "公園の遊具",
          media_type: "image",
          mime_type: "image/jpeg",
        },
      ],
      "wp:term": [
        [{ id: 11, name: "生活情報", slug: "living-info", taxonomy: "news_category" }],
      ],
    },
  },
  {
    id: 1003,
    date: ISO("2026-02-20"),
    date_gmt: ISO("2026-02-20", "00:00:00"),
    modified: ISO("2026-02-20"),
    modified_gmt: ISO("2026-02-20", "00:00:00"),
    slug: "haru-isseiseisou-2026",
    status: "publish",
    type: "news",
    link: "https://cms.hassamu-izumi.jp/news/haru-isseiseisou-2026/",
    title: { rendered: "春の一斉清掃のご案内" },
    content: {
      rendered: renderHtml([
        "恒例の春の一斉清掃を 2026年4月19日（日）9:00 より実施します。",
        "きれいな街づくりのため、皆様のご協力をお願いいたします。軍手・ゴミ袋は町内会で用意します。集合場所は各班のゴミステーション前です。",
      ]),
      protected: false,
    },
    excerpt: {
      rendered: "<p>恒例の春の一斉清掃を実施します。</p>",
      protected: false,
    },
    featured_media: 0,
    acf: { category: "行事", summary: "4/19（日）9:00集合。" },
  },
  {
    id: 1004,
    date: ISO("2026-02-12"),
    date_gmt: ISO("2026-02-12", "00:00:00"),
    modified: ISO("2026-02-12"),
    modified_gmt: ISO("2026-02-12", "00:00:00"),
    slug: "bousai-kunren-yotei",
    status: "publish",
    type: "news",
    link: "https://cms.hassamu-izumi.jp/news/bousai-kunren-yotei/",
    title: { rendered: "防災訓練（5月予定）の事前告知" },
    content: {
      rendered: renderHtml([
        "5月中旬に発寒小学校をお借りして防災訓練を実施予定です。詳細は次号の広報でお知らせします。",
        "炊き出し体験・AED講習・避難所運営ゲームを予定しています。",
      ]),
      protected: false,
    },
    excerpt: {
      rendered: "<p>5月中旬に防災訓練を実施予定です。</p>",
      protected: false,
    },
    featured_media: 0,
    acf: { category: "防災", summary: "5月中旬・発寒小学校で実施予定。" },
  },
  {
    id: 1005,
    date: ISO("2026-02-05"),
    date_gmt: ISO("2026-02-05", "00:00:00"),
    modified: ISO("2026-02-05"),
    modified_gmt: ISO("2026-02-05", "00:00:00"),
    slug: "line-koushiki-junbi",
    status: "publish",
    type: "news",
    link: "https://cms.hassamu-izumi.jp/news/line-koushiki-junbi/",
    title: { rendered: "LINE公式アカウント開設準備のお知らせ" },
    content: {
      rendered: renderHtml([
        "町内会のLINE公式アカウント開設に向けて準備を進めています。開設後は回覧板・行事案内をLINEでもお届けします。",
        "紙の回覧板は引き続き継続しますので、LINE登録は任意です。",
      ]),
      protected: false,
    },
    excerpt: {
      rendered: "<p>LINE公式アカウント開設準備中です。</p>",
      protected: false,
    },
    featured_media: 0,
    acf: { category: "お知らせ", summary: "LINE公式アカウント開設準備中。" },
  },
];

export const mockWpBroadcastArchive: WpBroadcastArchive[] = [
  {
    id: 1101,
    date: ISO("2026-03-01"),
    date_gmt: ISO("2026-03-01", "00:00:00"),
    modified: ISO("2026-03-01"),
    modified_gmt: ISO("2026-03-01", "00:00:00"),
    slug: "kouhou-2026-03",
    status: "publish",
    type: "broadcast_archive",
    link: "https://cms.hassamu-izumi.jp/broadcast/kouhou-2026-03/",
    title: { rendered: "発寒泉だより 2026年3月号" },
    content: {
      rendered: renderHtml([
        "総会のご案内、春の一斉清掃、ゴミ収集の変更点をまとめました。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>総会・清掃・ゴミ収集の最新情報。</p>", protected: false },
    featured_media: 0,
    acf: {
      issue_date: "2026-03-01",
      issue_number: "2026-03",
      pdf_url: "https://cms.hassamu-izumi.jp/wp-content/uploads/2026/03/kouhou-2026-03.pdf",
      pdf_size_bytes: 1_240_000,
      page_count: 4,
    },
  },
  {
    id: 1102,
    date: ISO("2026-02-01"),
    date_gmt: ISO("2026-02-01", "00:00:00"),
    modified: ISO("2026-02-01"),
    modified_gmt: ISO("2026-02-01", "00:00:00"),
    slug: "kouhou-2026-02",
    status: "publish",
    type: "broadcast_archive",
    link: "https://cms.hassamu-izumi.jp/broadcast/kouhou-2026-02/",
    title: { rendered: "発寒泉だより 2026年2月号" },
    content: {
      rendered: renderHtml(["雪まつり報告、除雪当番の振り返り、節分行事のご案内。"]),
      protected: false,
    },
    excerpt: { rendered: "<p>雪まつり報告ほか。</p>", protected: false },
    featured_media: 0,
    acf: {
      issue_date: "2026-02-01",
      issue_number: "2026-02",
      pdf_url: "https://cms.hassamu-izumi.jp/wp-content/uploads/2026/02/kouhou-2026-02.pdf",
      pdf_size_bytes: 1_080_000,
      page_count: 4,
    },
  },
  {
    id: 1103,
    date: ISO("2026-01-01"),
    date_gmt: ISO("2026-01-01", "00:00:00"),
    modified: ISO("2026-01-01"),
    modified_gmt: ISO("2026-01-01", "00:00:00"),
    slug: "kouhou-2026-01",
    status: "publish",
    type: "broadcast_archive",
    link: "https://cms.hassamu-izumi.jp/broadcast/kouhou-2026-01/",
    title: { rendered: "発寒泉だより 2026年1月号" },
    content: {
      rendered: renderHtml(["新年のご挨拶、もちつき大会報告、令和8年度予算案。"]),
      protected: false,
    },
    excerpt: { rendered: "<p>新年号。</p>", protected: false },
    featured_media: 0,
    acf: {
      issue_date: "2026-01-01",
      issue_number: "2026-01",
      pdf_url: "https://cms.hassamu-izumi.jp/wp-content/uploads/2026/01/kouhou-2026-01.pdf",
      pdf_size_bytes: 1_320_000,
      page_count: 6,
    },
  },
  {
    id: 1104,
    date: ISO("2025-12-01"),
    date_gmt: ISO("2025-12-01", "00:00:00"),
    modified: ISO("2025-12-01"),
    modified_gmt: ISO("2025-12-01", "00:00:00"),
    slug: "kouhou-2025-12",
    status: "publish",
    type: "broadcast_archive",
    link: "https://cms.hassamu-izumi.jp/broadcast/kouhou-2025-12/",
    title: { rendered: "発寒泉だより 2025年12月号" },
    content: { rendered: renderHtml(["年末年始のゴミ収集・除雪体制について。"]), protected: false },
    excerpt: { rendered: "<p>年末年始号。</p>", protected: false },
    featured_media: 0,
    acf: {
      issue_date: "2025-12-01",
      issue_number: "2025-12",
      pdf_url: "https://cms.hassamu-izumi.jp/wp-content/uploads/2025/12/kouhou-2025-12.pdf",
      pdf_size_bytes: 980_000,
      page_count: 4,
    },
  },
  {
    id: 1105,
    date: ISO("2025-11-01"),
    date_gmt: ISO("2025-11-01", "00:00:00"),
    modified: ISO("2025-11-01"),
    modified_gmt: ISO("2025-11-01", "00:00:00"),
    slug: "kouhou-2025-11",
    status: "publish",
    type: "broadcast_archive",
    link: "https://cms.hassamu-izumi.jp/broadcast/kouhou-2025-11/",
    title: { rendered: "発寒泉だより 2025年11月号" },
    content: { rendered: renderHtml(["秋の文化祭報告、冬支度のご案内。"]), protected: false },
    excerpt: { rendered: "<p>文化祭報告。</p>", protected: false },
    featured_media: 0,
    acf: {
      issue_date: "2025-11-01",
      issue_number: "2025-11",
      pdf_url: "https://cms.hassamu-izumi.jp/wp-content/uploads/2025/11/kouhou-2025-11.pdf",
      pdf_size_bytes: 1_150_000,
      page_count: 4,
    },
  },
];

export const mockWpFaqs: WpFaq[] = [
  {
    id: 1201,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "gomi-station-yogore",
    status: "publish",
    type: "faq",
    link: "https://cms.hassamu-izumi.jp/faq/gomi-station-yogore/",
    title: { rendered: "ゴミステーションが汚れている時は？" },
    content: {
      rendered: renderHtml([
        "清掃当番の班、または衛生部までお知らせください。お問い合わせフォームからもご連絡いただけます。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "", protected: false },
    featured_media: 0,
    acf: { category: "ゴミ", sort_order: 1 },
  },
  {
    id: 1202,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "taikai-tetsuduki",
    status: "publish",
    type: "faq",
    link: "https://cms.hassamu-izumi.jp/faq/taikai-tetsuduki/",
    title: { rendered: "町内会を退会したい場合は？" },
    content: {
      rendered: renderHtml([
        "班長または事務局へ直接ご連絡ください。退会の手続き自体は簡単で、いつでも可能です。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "", protected: false },
    featured_media: 0,
    acf: { category: "会員", sort_order: 2 },
  },
  {
    id: 1203,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "hikkoshi-tetsuduki",
    status: "publish",
    type: "faq",
    link: "https://cms.hassamu-izumi.jp/faq/hikkoshi-tetsuduki/",
    title: { rendered: "引っ越してきました。何をすればよいですか？" },
    content: {
      rendered: renderHtml([
        "お住まいの番地から該当の班を「街区マップ」で確認のうえ、班長へご挨拶ください。",
        "LINE登録ページから登録すると、回覧板やお知らせがスマホに届きます。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "", protected: false },
    featured_media: 0,
    acf: { category: "会員", sort_order: 3 },
  },
  {
    id: 1204,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "line-touroku-hissu",
    status: "publish",
    type: "faq",
    link: "https://cms.hassamu-izumi.jp/faq/line-touroku-hissu/",
    title: { rendered: "LINE登録は必須ですか？" },
    content: {
      rendered: renderHtml([
        "任意です。未登録の方には引き続き紙の回覧板をお届けします。LINE登録をするとよりタイムリーに情報が届きます。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "", protected: false },
    featured_media: 0,
    acf: { category: "LINE", sort_order: 4 },
  },
  {
    id: 1205,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "kojinjouhou-kyouyu",
    status: "publish",
    type: "faq",
    link: "https://cms.hassamu-izumi.jp/faq/kojinjouhou-kyouyu/",
    title: { rendered: "個人情報は連合町内会と共有されますか？" },
    content: {
      rendered: renderHtml([
        "いいえ。発寒泉町内会で集めた名簿は、連合町内会・他団体・行政には渡しません。詳細はプライバシーポリシーをご確認ください。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "", protected: false },
    featured_media: 0,
    acf: { category: "個人情報", sort_order: 5 },
  },
];

export const mockWpEvents: WpEvent[] = [
  {
    id: 1301,
    date: ISO("2026-03-15"),
    date_gmt: ISO("2026-03-15", "00:00:00"),
    modified: ISO("2026-03-15"),
    modified_gmt: ISO("2026-03-15", "00:00:00"),
    slug: "shinshun-mochitsuki-2027",
    status: "publish",
    type: "event",
    link: "https://cms.hassamu-izumi.jp/events/shinshun-mochitsuki-2027/",
    title: { rendered: "新春もちつき大会" },
    content: {
      rendered: renderHtml([
        "地域の皆様と新年を祝う恒例行事です。つきたてのお餅とおしるこをご用意してお待ちしております。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>新年恒例のもちつき大会。</p>", protected: false },
    featured_media: 2301,
    acf: {
      event_date: "2027-01-12T10:00:00+09:00",
      event_end_date: "2027-01-12T13:00:00+09:00",
      location: "発寒泉公園",
      capacity: 150,
      is_canceled: false,
    },
    _embedded: {
      "wp:featuredmedia": [
        {
          id: 2301,
          source_url:
            "https://images.unsplash.com/photo-1590559063737-01e40398698c?auto=format&fit=crop&q=80&w=1200",
          alt_text: "もちつきの臼と杵",
          media_type: "image",
          mime_type: "image/jpeg",
        },
      ],
    },
  },
  {
    id: 1302,
    date: ISO("2026-03-10"),
    date_gmt: ISO("2026-03-10", "00:00:00"),
    modified: ISO("2026-03-10"),
    modified_gmt: ISO("2026-03-10", "00:00:00"),
    slug: "haru-isseiseisou-event-2026",
    status: "publish",
    type: "event",
    link: "https://cms.hassamu-izumi.jp/events/haru-isseiseisou-event-2026/",
    title: { rendered: "春の一斉清掃" },
    content: {
      rendered: renderHtml([
        "きれいな街づくりのため、皆様のご協力をお願いいたします。軍手・ゴミ袋は町内会で用意します。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>春の一斉清掃。</p>", protected: false },
    featured_media: 0,
    acf: {
      event_date: "2026-04-19T09:00:00+09:00",
      event_end_date: "2026-04-19T11:00:00+09:00",
      location: "各班ゴミステーション前",
      is_canceled: false,
    },
  },
  {
    id: 1303,
    date: ISO("2026-04-01"),
    date_gmt: ISO("2026-04-01", "00:00:00"),
    modified: ISO("2026-04-01"),
    modified_gmt: ISO("2026-04-01", "00:00:00"),
    slug: "bousai-kunren-2026-05",
    status: "publish",
    type: "event",
    link: "https://cms.hassamu-izumi.jp/events/bousai-kunren-2026-05/",
    title: { rendered: "防災訓練2026" },
    content: {
      rendered: renderHtml([
        "AED講習・炊き出し体験・避難所運営ゲームを実施します。事前申込制（先着100名）。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>AED講習・炊き出しなど。</p>", protected: false },
    featured_media: 0,
    acf: {
      event_date: "2026-05-24T09:00:00+09:00",
      event_end_date: "2026-05-24T12:00:00+09:00",
      location: "発寒小学校 体育館",
      capacity: 100,
      registration_url: "https://liff.hassamu-izumi.jp/events/bousai-2026-05",
      is_canceled: false,
    },
  },
  {
    id: 1304,
    date: ISO("2026-05-01"),
    date_gmt: ISO("2026-05-01", "00:00:00"),
    modified: ISO("2026-05-01"),
    modified_gmt: ISO("2026-05-01", "00:00:00"),
    slug: "natsumatsuri-2026",
    status: "publish",
    type: "event",
    link: "https://cms.hassamu-izumi.jp/events/natsumatsuri-2026/",
    title: { rendered: "発寒泉夏祭り" },
    content: {
      rendered: renderHtml([
        "盆踊り・縁日・抽選会を予定しています。雨天時は翌週に順延。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>夏祭り。</p>", protected: false },
    featured_media: 0,
    acf: {
      event_date: "2026-08-08T17:00:00+09:00",
      event_end_date: "2026-08-08T20:30:00+09:00",
      location: "発寒泉公園 中央広場",
      capacity: 500,
      is_canceled: false,
    },
  },
  {
    id: 1305,
    date: ISO("2026-06-01"),
    date_gmt: ISO("2026-06-01", "00:00:00"),
    modified: ISO("2026-06-01"),
    modified_gmt: ISO("2026-06-01", "00:00:00"),
    slug: "aki-bunkasai-2026",
    status: "publish",
    type: "event",
    link: "https://cms.hassamu-izumi.jp/events/aki-bunkasai-2026/",
    title: { rendered: "秋の文化祭" },
    content: {
      rendered: renderHtml([
        "町内会館にて作品展示・発表会を開催します。出展者を募集中（締切10/15）。",
      ]),
      protected: false,
    },
    excerpt: { rendered: "<p>秋の文化祭。</p>", protected: false },
    featured_media: 0,
    acf: {
      event_date: "2026-10-25T10:00:00+09:00",
      event_end_date: "2026-10-25T15:00:00+09:00",
      location: "発寒泉町内会館",
      registration_url: "https://liff.hassamu-izumi.jp/events/bunkasai-2026",
      is_canceled: false,
    },
  },
];
